# EcoScalpel runs on pull requests (PR) and posts PR comments.
# If you use EcoScalpel Cloud, EcoScalpel also runs on main/master branch pushes so the dashboard is updated.
# The GitHub Action docs (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) describe other trigger options.
on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main
      - master

env:
  # If you use private modules you'll need this env variable to use
  # the same ssh-agent socket value across all jobs & steps.
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  # This stage runs the EcoScalpel CLI and posts PR comments.
  # It also updates PR comments when the PR is updated (synchronize event).
  ecoscalpel-pull-request-checks:
    name: EcoScalpel Pull Request Checks
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments
    # env:
      # If you store Terraform variables or modules in a 3rd party such as TFC or Spacelift,
      # specify the following so EcoScalpel can automatically retrieve them.
      # See https://github.com/didier-segura/actions for details.
      #   ECOSCALPEL_TERRAFORM_CLOUD_TOKEN: ${{ secrets.TFC_TOKEN }}
      #   ECOSCALPEL_TERRAFORM_CLOUD_HOST: app.terraform.io
    steps:
      # If you use private modules, add an environment variable or secret
      # called GIT_SSH_KEY with your private key, so EcoScalpel CLI can access
      # private repositories (similar to how Terraform/Terragrunt does).
      # - name: add GIT_SSH_KEY
      #   run: |
      #     ssh-agent -a $SSH_AUTH_SOCK
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.GIT_SSH_KEY }}" | tr -d '\r' | ssh-add -
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup EcoScalpel
        uses: didier-segura/actions/setup@v0.1.9
        # See https://github.com/didier-segura/actions/tree/main/setup for other inputs
        with:
          api-key: ${{ secrets.ECOSCALPEL_API_KEY }}
          version: prod-0.0.7

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # Generate EcoScalpel JSON file as the baseline.
      - name: Generate EcoScalpel cost estimate baseline
        run: |
          ecoscalpel breakdown --path=. \
                               --format=json \
                               --out-file=/tmp/ecoscalpel-base.json

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # Generate an EcoScalpel diff and save it to a JSON file.
      - name: Generate EcoScalpel diff
        run: |
          ecoscalpel diff --path=. \
                          --format=json \
                          --compare-to=/tmp/ecoscalpel-base.json \
                          --out-file=/tmp/ecoscalpel.json

      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      - name: Post EcoScalpel comment
        run: |
            ecoscalpel comment github --path=/tmp/ecoscalpel.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{ github.token }} \
                                      --pull-request=${{ github.event.pull_request.number }} \
                                      --behavior=update

  # Run EcoScalpel on default branch and update EcoScalpel Cloud
  ecoscalpel-default-branch-update:
    # If you use private modules, or store Terraform variables or modules in a 3rd party
    # such as TFC or Spacelift, include the same steps/variables as the ecoscalpel-pull-request-checks job
    name: EcoScalpel Default Branch Update
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Setup EcoScalpel
        uses: didier-segura/actions/setup@v0.1.9
        with:
          api-key: ${{ secrets.ECOSCALPEL_API_KEY }}
          version: prod-0.0.7

      - name: Checkout main/master branch
        uses: actions/checkout@v4

      - name: Run EcoScalpel on default branch and update EcoScalpel Cloud
        run: |
          ecoscalpel breakdown --path=. \
                    --format=json \
                    --out-file=ecoscalpel.json

          ecoscalpel upload --path=ecoscalpel.json || echo "Always pass main branch runs even if there are policy failures"

  # Update PR status in EcoScalpel Cloud
  ecoscalpel-pull-request-status-update:
    name: EcoScalpel PR Status Update
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: EcoScalpel PR Status Update
      run: |
        PR_STATUS="MERGED"
        if [[ ${{ github.event.pull_request.merged }} = false ]]; then PR_STATUS="CLOSED"; fi

        echo "Updating status of ${{ github.event.pull_request.html_url }} to $PR_STATUS"
        curl -i \
          --request POST \
          --header "Content-Type: application/json" \
          --header "X-API-Key: $ECOSCALPEL_API_KEY" \
          --data "{ \"query\": \"mutation {updatePullRequestStatus( url: \\\"${{ github.event.pull_request.html_url }}\\\", status: $PR_STATUS )}\" }" \
          "https://dashboard.api.ecoscalpel.io/graphql";
      env:
        ECOSCALPEL_API_KEY: ${{ secrets.ECOSCALPEL_API_KEY }}
